export { shopifyFetch } from "./client";
export {
  FEATURED_PRODUCTS_QUERY,
  FEATURED_COLLECTIONS_QUERY,
  ALL_COLLECTIONS_QUERY,
  COLLECTION_BY_HANDLE_QUERY,
  ALL_PRODUCTS_QUERY,
  PRODUCT_BY_HANDLE_QUERY,
  CREATE_CART_MUTATION,
  ADD_TO_CART_MUTATION,
  UPDATE_CART_LINE_MUTATION,
  REMOVE_CART_LINE_MUTATION,
} from "./queries";
export {
  getProduct,
  getProducts,
  getProductsByCollection,
  getCollections,
  getCollection,
  createCart,
  addToCart,
  updateCartLine,
  removeCartLine,
  optimisticAddToCart,
  optimisticUpdateCartLine,
  optimisticRemoveCartLine,
} from "./api";
export type {
  ShopifyProduct,
  ShopifyCollection,
  ShopifyImage,
  ShopifyMoney,
  ShopifyVariant,
  ShopifyCart,
  ShopifyCartLine,
  PageInfo,
  FeaturedProductsResponse,
  FeaturedCollectionsResponse,
  AllCollectionsResponse,
  CollectionByHandleResponse,
  AllProductsResponse,
  ProductByHandleResponse,
  CartResponse,
  CartCreateResponse,
  CartLinesAddResponse,
  CartLinesUpdateResponse,
  CartLinesRemoveResponse,
} from "./types";
